# impoting library

In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

# pandas series with python lists

In [ ]:
lst=[1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]

In [ ]:
series=pd.Series(lst)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
empty=pd.Series([])
empty

Series([], dtype: object)

In [ ]:
a=pd.Series(['p','q','r','s','t'],index=[10,11,12,13,14])
a

10    p
11    q
12    r
13    s
14    t
dtype: object

In [ ]:
b=pd.Series(['p','q','r','s','t'],index=[10,11,12,13,14],name='alphabets')
b

10    p
11    q
12    r
13    s
14    t
Name: alphabets, dtype: object

In [ ]:
scaler_series=pd.Series(0.5)
scaler_series

0    0.5
dtype: float64

In [ ]:
scaler_series=pd.Series(0.5,index=[1,2,3])
scaler_series

1    0.5
2    0.5
3    0.5
dtype: float64



> pandas series with python dictionary

In [ ]:
dict_series=pd.Series({'p':1,'q':2,'r':3,'s':4,'t':5})
dict_series

p    1
q    2
r    3
s    4
t    5
dtype: int64

In [ ]:
print(dict_series[0])

1

/tmp/ipykernel_7562/1564464665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(dict_series[0])

In [ ]:
dict_series[0:3]

p    1
q    2
r    3
dtype: int64

In [ ]:
max(dict_series)

5

In [ ]:
dict_series=pd.Series({'p':[1,2,3],'q':[2,6,7],'r':[3,4,5],'s':[2,5,4],'t':[2,7,5]})
dict_series

p    [1, 2, 3]
q    [2, 6, 7]
r    [3, 4, 5]
s    [2, 5, 4]
t    [2, 7, 5]
dtype: object

#  Pandas DataFrame and Reading CSV Files

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

# data frame using list

In [ ]:
lst=[1,2,3,4,5]
df=pd.DataFrame(lst)
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
lst=[[1,2,3,4,5],[2,4,6,8,3]]
df=pd.DataFrame(lst)
print(df)

   0  1  2  3  4
0  1  2  3  4  5
1  2  4  6  8  3

In [ ]:
a=[{'a':5,'b':6,'c':7,'d':4,'e':54},
 {'a':0,'b':9,'c':8,'d':98,'e':57}]   # dictionary keys represnt column names
df=pd.DataFrame(a)
df

   a  b  c   d   e
0  5  6  7   4  54
1  0  9  8  98  57

In [ ]:
b={'rollno':pd.Series([1,2,3,4,5])
   ,'name':pd.Series(['a','b','c','d','e'])
   ,'marks':pd.Series([10,20,30,40,50])
   }

df=pd.DataFrame(b)
df

   rollno name  marks
0       1    a     10
1       2    b     20
2       3    c     30
3       4    d     40
4       5    e     50

In [ ]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/15uRinXHFe3p44ggg5fybTudqYszrUWe6gB_suXpOshc/edit#gid=0

#Reading CSv (common separated values) as DataFrames

In [ ]:
df=pd.read_csv(r'/content/customers-100.csv')
df

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
type(df)

pandas.core.frame.DataFrame

# dataframe functions

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(r'/content/customers-100.csv')

In [ ]:
df.columns

Index(['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City',
       'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date',
       'Website'],
      dtype='object')

In [ ]:
df.shape

(100, 12)

In [ ]:
df.size

1200

In [ ]:
df.head()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/

In [ ]:
df.head(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/

In [ ]:
df.tail()

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
df.tail(2)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [ ]:
df.describe() #description of numerical data

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB

#Handling the Null values/missing values

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv(r'/content/Diabetes Missing Data.csv')
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [ ]:
df.isnull()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
763,False,False,False,False,False,False,False,False,False
764,False,False,False,False,True,False,False,False,False
765,False,False,False,False,False,False,False,False,False
766,False,False,False,True,True,False,False,False,False
767,False,False,False,False,True,False,False,False,False

In [ ]:
df.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(652)

# dropping rows with NaN values

In [ ]:
df.shape

(768, 9)

In [ ]:
df2=df.dropna() # default axis =0

dropna() is the opposite kind of operation compared to isnull().

Instead of detecting missing values, dropna() removes them.

In [ ]:
df2.shape

(392, 9)

# droppping columns with NaN values

In [ ]:
df3=df.dropna(axis=1)  #axis =1 for columns

In [ ]:
df3.shape

(768, 4)

In [ ]:
df.dropna(how='any')  # if any row value is null then remove that row

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
6,3,78.0,50.0,32.0,88.0,31.0,0.248,26,1
8,2,197.0,70.0,45.0,543.0,30.5,0.158,53,1
13,1,189.0,60.0,23.0,846.0,30.1,0.398,59,1
...,...,...,...,...,...,...,...,...,...
753,0,181.0,88.0,44.0,510.0,43.3,0.222,26,1
755,1,128.0,88.0,39.0,110.0,36.5,1.057,37,1
760,2,88.0,58.0,26.0,16.0,28.4,0.766,22,0
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0

In [ ]:
df.dropna(how='all') # if all rows values is null then remove that row

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [ ]:
df.dropna(inplace=True) #Remove rows with missing values (NaN) and directly modify the original DataFrame

In [ ]:
df.shape

(392, 9)

# Filling the null values

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/Diabetes Missing Data.csv')
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [ ]:
df.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [ ]:
df.fillna(0)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23,0

In [ ]:
df.fillna(2)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,2.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,2.0,26.6,0.351,31,0
2,8,183.0,64.0,2.0,2.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,2.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,2.0,2.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,2.0,30.4,0.315,23,0

In [ ]:
df.fillna({'Glucose':0,'Diastolic_BP':24,'Skin_Fold':34})

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,34.0,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,34.0,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [ ]:
df.fillna(method='ffill') #forward fill -previous value is filled inplace of null value

/tmp/ipykernel_5897/2380459296.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill') #forward fill -previous value is filled inplace of null value

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,29.0,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,180.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,23.0,112.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,112.0,30.4,0.315,23,0

In [ ]:
df.fillna(method='ffill',axis=1) #forward fill -if we put axis =1 then previous column same row value is filled in cureent column

In [ ]:
df['Glucose'].fillna(value=df['Diabetes_Pedigree'].mean())

0      148.0
1       85.0
2      183.0
3       89.0
4      137.0
       ...
763    101.0
764    122.0
765    121.0
766    126.0
767     93.0
Name: Glucose, Length: 768, dtype: float64

# Replace()

In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/Diabetes Missing Data.csv')
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [5]:
df.replace(to_replace=148,value=5)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,5.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [6]:
df.replace(137,90)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,90.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [8]:
df.replace(to_replace=[101,121,126,72,23,48],value='A')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,A,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,A,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,A,76.0,A,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,A,A,A,112.0,26.2,0.245,30,0
766,1,A,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,A,0

In [10]:
df.replace(to_replace=[101,121,126,72,23,48],value=['A','B','C','D','E','F'])

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,D,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,E,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,A,76.0,F,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,B,D,E,112.0,26.2,0.245,30,0
766,1,C,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,E,0

In [13]:
df['Glucose'].replace(to_replace=[101,121,126,72,23,48],value=['A','B','C','D','E','F'])

0      148.0
1       85.0
2      183.0
3       89.0
4      137.0
       ...
763        A
764    122.0
765        B
766        C
767     93.0
Name: Glucose, Length: 768, dtype: object

In [14]:
df['Glucose'].replace(to_replace=[101,121,126,72,23,48],value=['A','B','C','D','E','F'],inplace=True)
df

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,A,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,B,72.0,23.0,112.0,26.2,0.245,30,0
766,1,C,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [15]:
df.replace('[A-Za-z]',0)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,A,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,B,72.0,23.0,112.0,26.2,0.245,30,0
766,1,C,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [16]:
df.replace('[A-Za-z]',0 ,regex=True)

/tmp/ipykernel_9453/3887451312.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('[A-Za-z]',0 ,regex=True)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,0.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,0.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,0.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [18]:
df.replace(to_replace=137,method='ffill')

/tmp/ipykernel_9453/1752212732.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  df.replace(to_replace=137,method='ffill')

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,89.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,A,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,B,72.0,23.0,112.0,26.2,0.245,30,0
766,1,C,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

# loc

In [20]:
import pandas as pd

In [22]:
df=pd.read_csv('/content/Diabetes Missing Data.csv')
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [23]:
df.loc[1]

Pregnant              1.000
Glucose              85.000
Diastolic_BP         66.000
Skin_Fold            29.000
Serum_Insulin           NaN
BMI                  26.600
Diabetes_Pedigree     0.351
Age                  31.000
Class                 0.000
Name: 1, dtype: float64

In [25]:
df.loc[[2,3,4,5]]

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
5,5,116.0,74.0,NaN,NaN,25.6,0.201,30,0

In [26]:
df.loc[4,'Glucose']

np.float64(137.0)

In [27]:
df.loc[2:5,['Glucose']]

   Glucose
2    183.0
3     89.0
4    137.0
5    116.0

In [28]:
df.loc[df['Glucose']<300]

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23,0

In [29]:
df.loc[df['Glucose']>30,['Diastolic_BP']]

     Diastolic_BP
0            72.0
1            66.0
2            64.0
3            66.0
4            40.0
..            ...
763          76.0
764          70.0
765          72.0
766          60.0
767          70.0

[763 rows x 1 columns]

#iloc() -->   index location ,it gives row

In [30]:
df.iloc[0]

Pregnant               6.000
Glucose              148.000
Diastolic_BP          72.000
Skin_Fold             35.000
Serum_Insulin            NaN
BMI                   33.600
Diabetes_Pedigree      0.627
Age                   50.000
Class                  1.000
Name: 0, dtype: float64

In [31]:
df.iloc[[2,3,4]]

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [33]:
df.iloc[:1]

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1

In [34]:
df.iloc[0:5,1]

0    148.0
1     85.0
2    183.0
3     89.0
4    137.0
Name: Glucose, dtype: float64

In [35]:
df.iloc[0:5,1:4]

   Glucose  Diastolic_BP  Skin_Fold
0    148.0          72.0       35.0
1     85.0          66.0       29.0
2    183.0          64.0        NaN
3     89.0          66.0       23.0
4    137.0          40.0       35.0

#groupby() function

In [36]:
import pandas as pd
df=pd.read_csv('/content/Diabetes Missing Data.csv')
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [37]:
branch_group=df.groupby(by='Glucose')
branch_group

In [39]:
branch_group.groups

{44.0: [62], 56.0: [680], 57.0: [146, 537], 61.0: [352], 62.0: [76], 65.0: [737], 67.0: [596], 68.0: [520, 617, 672], 71.0: [47, 97, 273, 461], 72.0: [403], 73.0: [55, 183, 589], 74.0: [81, 234, 462, 466], 75.0: [174, 505], 76.0: [113, 518], 77.0: [302, 534], 78.0: [6, 117, 290, 570], 79.0: [74, 173, 232], 80.0: [90, 310, 432, 494, 659, 705], 81.0: [92, 103, 210, 368, 497, 747], 82.0: [398, 450, 593], 83.0: [82, 108, 418, 441, 490, 720], 84.0: [60, 133, 372, 483, 501, 508, 510, 543, 551, 554], 85.0: [1, 104, 176, 194, 218, 482, 559], 86.0: [253, 457, 532], 87.0: [172, 180, 225, 331, 377, 525, 562], 88.0: [32, 52, 125, 158, 358, 463, 544, 553, 760], 89.0: [3, 112, 431, 491, 597, 762], 90.0: [38, 149, 252, 353, 354, 383, 434, 542, 625, 643, 694], 91.0: [240, 241, 452, 512, 513, 533, 564, 650, 674], 92.0: [33, 96, 254, 350, 567, 607, 621, 634, 729], 93.0: [98, 137, 379, 585, 677, 709, 767], 94.0: [421, 426, 503, 623, 629, 637, 717], 95.0: [68, 77, 109, 262, 334, 341, 344, 400, 429, 447, 565, 682, 735], 96.0: [106, 134, 208, 265, 288, 396, 504, 601], 97.0: [27, 118, 416, 438, 467, 526, 556, 638, 719], 98.0: [376, 573, 668], 99.0: [21, 65, 119, 156, 203, 316, 348, 365, 430, 488, 492, 514, 563, 566, 671, 697, 738], 100.0: [15, 57, 70, 87, 136, 163, 224, 275, 298, 389, 390, 446, 454, 540, 583, 639, 745], 101.0: [51, 83, 226, 270, 367, 407, 656, 679, 763], 102.0: [37, 145, 161, 170, 268, 328, 410, 422, 631, 640, 714, 739, 741], 103.0: [18, 35, 48, 50, 204, 362, 558, 587, 644], 104.0: [165, 239, 277, 448, 635, 636], 105.0: [49, 59, 129, 139, 196, 329, 373, 381, 387, 476, 536, 613, 734], 106.0: [42, 86, 141, 147, 250, 274, 276, 311, 333, 610, 615, 654, 733, 758], 107.0: [17, 89, 122, 197, 291, 380, 439, 531, 649, 687, 690], 108.0: [142, 143, 202, 271, 279, 284, 289, 443, 576, 600, 624, 718, 752], 109.0: [30, 66, 67, 157, 188, 198, 216, 314, 382, 581, 599, 742], 110.0: [10, 85, 168, 496, 557, 704], 111.0: [39, 121, 169, 190, 205, 249, 256, 529, 572, 590, 609, 632, 667, 724], 112.0: [79, 214, 219, 299, 315, 321, 324, 411, 591, 618, 620, 665, 725], 113.0: [80, 124, 200, 255, 313], 114.0: [64, 151, 162, 257, 278, 474, 477, 522, 552, 630, 721], 115.0: [7, 19, 303, 318, 337, 406, 423, 464, 664, 706], 116.0: [5, 347, 386, 393, 527, 550, 726], 117.0: [29, 128, 229, 336, 442, 444, 500, 528, 616, 651, 723], 118.0: [16, 127, 330, 371, 577, 699], 119.0: [23, 181, 222, 243, 287, 385, 420, 453, 472, 575, 619], 120.0: [126, 167, 305, 449, 460, 468, 509, 653, 657, 731, 740], 121.0: [569, 582, 678, 692, 751, 765], 122.0: [34, 99, 131, 233, 246, 272, 326, 343, 374, 530, 700, 764], 123.0: [91, 191, 264, 405, 481, 594, 652, 673, 757], 124.0: [116, 248, 309, 322, 366, 465, 521, 555, 584, 602, 605], 125.0: [9, 25, 102, 135, 217, 356, 384, 493, 517, 524, 560, 626, 683, 701], 126.0: [20, 72, 105, 297, 345, 478, 711, 736, 766], 127.0: [395, 538, 658, 698, 707], 128.0: [140, 187, 267, 292, 293, 308, 541, 628, 633, 641, 755], 129.0: [73, 138, 177, 251, 281, 320, 357, 419, 519, 539, 685, 693, 703, 712], 130.0: [179, 340, 507, 523, 571, 686, 730], 131.0: [78, 164, 392, 397, 547], 132.0: [123, 479, 535, 592, 627], 133.0: [41, 61, 282, 369, 578], 134.0: [93, 171, 231, 451, 459, 713], 135.0: [193, 428, 456, 485], 136.0: [88, 150, 285, 402, 473, 648, 684, 750], 137.0: [4, 84, 307, 351, 401, 471, 475, 756], 138.0: [36, 201, 266, 414, 614], 139.0: [12, 71, 189, 242, 346, 433, 486, 511], 140.0: [213, 375, 436, 688, 743], 141.0: [63, 184, 261, 435, 727], 142.0: [94, 223, 230, 263, 695], 143.0: [24, 178, 412, 413, 574, 586], 144.0: [95, 107, 301, 388, 417, 470, 689], 145.0: [28, 484, 516, 663, 666], 146.0: [46, 58, 69, 115, 244, 269, 280, 296, 363], 147.0: [26, 148, 211, 364, 437, 642, 746], 148.0: [0, 166, 199, 458], 149.0: [722], 150.0: [54, 304, 603], 151.0: [101, 160, 215, 295, 424, 580], 152.0: [155, 323, 338, 608], 153.0: [153, 744], 154.0: [144, 469, 499, 568, 669, 754], 155.0: [111, 259, 286, 312, 655], 156.0: [152, 378, 676], 157.0: [325, 645], 158.0: [31, 195, 221, 361, 394, 480, 691, 710], 159.0: [44, 192], 160.0: [114], 161.0: [283, 294, 306], 162.0: [120, 207, 227, 660, 681, 749], ...}

In [43]:
df.groupby(['Glucose','Diastolic_BP']).groups

{(44.0, 62.0): [62], (56.0, 56.0): [680], (57.0, 60.0): [537], (57.0, 80.0): [146], (61.0, 82.0): [352], (62.0, 78.0): [76], (65.0, 72.0): [737], (67.0, 76.0): [596], (68.0, 62.0): [617], (68.0, 70.0): [520], (68.0, 106.0): [672], (71.0, 48.0): [97], (71.0, 62.0): [461], (71.0, 70.0): [47], (71.0, 78.0): [273], (72.0, 78.0): [403], (73.0, 50.0): [55], (73.0, nan): [589], (73.0, 60.0): [183], (74.0, 52.0): [466], (74.0, 68.0): [234], (74.0, nan): [81], (74.0, 70.0): [462], (75.0, 64.0): [174], (75.0, 82.0): [505], (76.0, 60.0): [518], (76.0, 62.0): [113], (77.0, 56.0): [534], (77.0, 82.0): [302], (78.0, 48.0): [117], (78.0, 50.0): [6], (78.0, 70.0): [570], (78.0, 88.0): [290], (79.0, 60.0): [173], (79.0, 75.0): [74], (79.0, 80.0): [232], (80.0, nan): [494], (80.0, 55.0): [90], (80.0, 66.0): [310], (80.0, 74.0): [432], (80.0, 80.0): [705], (80.0, 82.0): [659], (81.0, 60.0): [210], (81.0, 72.0): [103, 497], (81.0, 74.0): [747], (81.0, 78.0): [92], (81.0, 86.0): [368], (82.0, 52.0): [593], (82.0, 64.0): [450], (82.0, 70.0): [398], (83.0, 58.0): [108], (83.0, 65.0): [490], (83.0, 66.0): [441], (83.0, 68.0): [418], (83.0, 78.0): [82], (83.0, 86.0): [720], (84.0, nan): [60], (84.0, 50.0): [508], (84.0, 64.0): [372, 554], (84.0, 68.0): [551], (84.0, 72.0): [501, 510], (84.0, 74.0): [133], (84.0, 82.0): [483], (84.0, 90.0): [543], (85.0, 55.0): [194], (85.0, 58.0): [482], (85.0, 65.0): [104], (85.0, 66.0): [1], (85.0, 74.0): [218, 559], (85.0, 78.0): [176], (86.0, 66.0): [532], (86.0, 68.0): [253, 457], (87.0, 68.0): [562], (87.0, 78.0): [225], (nan, 74.0): [182], (87.0, 80.0): [180], (87.0, nan): [172], (87.0, 58.0): [331], (87.0, 60.0): [377, 525], (88.0, 30.0): [125], (nan, 80.0): [349], (nan, 68.0): [342, 502], (88.0, 58.0): [32, 760], (88.0, 62.0): [553], (88.0, 66.0): [52], (88.0, 74.0): [158, 358], (88.0, 78.0): [463, 544], (89.0, 24.0): [597], (89.0, 62.0): [762], (89.0, 66.0): [3], (89.0, 74.0): [431], (89.0, 76.0): [112], (89.0, 90.0): [491], (90.0, 60.0): [694], (90.0, 62.0): [353, 383], (90.0, 68.0): [38, 434], (90.0, 70.0): [149], (90.0, 78.0): [354], (90.0, 80.0): [252], (90.0, 85.0): [542], ...}

# Povit table

In [44]:
import pandas as pd
df=pd.read_csv('/content/Diabetes Missing Data.csv')
df.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [46]:
pd.pivot_table(df,index='Glucose')  #it internally behaves like df.groupby('Glucose').mean()

,Age,BMI,Class,Diabetes_Pedigree,Diastolic_BP,Pregnant,Serum_Insulin,Skin_Fold
Glucose,,,,,,,,
44.0,36.000000,25.000000,0.00,0.587000,62.000000,5.000000,NaN,NaN
56.0,22.000000,24.200000,0.00,0.332000,56.000000,2.000000,45.0,28.0
57.0,54.000000,27.250000,0.00,0.415500,70.000000,4.500000,NaN,37.0
61.0,46.000000,34.400000,0.00,0.243000,82.000000,3.000000,NaN,28.0
62.0,41.000000,32.600000,0.00,0.391000,78.000000,7.000000,NaN,NaN
...,...,...,...,...,...,...,...,...
195.0,43.000000,28.000000,1.00,0.245500,70.000000,6.500000,145.0,33.0
196.0,42.333333,37.933333,1.00,0.643667,80.666667,5.333333,264.5,32.5
197.0,46.250000,31.950000,0.75,1.063250,71.000000,4.000000,643.5,61.0
198.0,28.000000,41.300000,1.00,0.502000,66.000000,0.000000,274.0,32.0
199.0,22.000000,42.900000,1.00,1.394000,76.000000,1.000000,NaN,43.0

In [47]:
pd.pivot_table(df,index='Glucose',aggfunc='sum') #Sums all other numeric columns for each group

,Age,BMI,Class,Diabetes_Pedigree,Diastolic_BP,Pregnant,Serum_Insulin,Skin_Fold
Glucose,,,,,,,,
44.0,36,25.0,0,0.587,62.0,5,0.0,0.0
56.0,22,24.2,0,0.332,56.0,2,45.0,28.0
57.0,108,54.5,0,0.831,140.0,9,0.0,37.0
61.0,46,34.4,0,0.243,82.0,3,0.0,28.0
62.0,41,32.6,0,0.391,78.0,7,0.0,0.0
...,...,...,...,...,...,...,...,...
195.0,86,56.0,2,0.491,140.0,13,145.0,33.0
196.0,127,113.8,3,1.931,242.0,16,529.0,65.0
197.0,185,127.8,3,4.253,284.0,16,1287.0,183.0
198.0,28,41.3,1,0.502,66.0,0,274.0,32.0
199.0,22,42.9,1,1.394,76.0,1,0.0,43.0

In [49]:
pd.pivot_table(df,index='Glucose',columns='Pregnant')

           Age                                                        ...  \
Pregnant    0     1     2     3     4     5     6     7     8     9   ...
Glucose                                                               ...
44.0       NaN   NaN   NaN   NaN   NaN  36.0   NaN   NaN   NaN   NaN  ...
56.0       NaN   NaN  22.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
57.0      67.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  41.0  ...
61.0       NaN   NaN   NaN  46.0   NaN   NaN   NaN   NaN   NaN   NaN  ...
62.0       NaN   NaN   NaN   NaN   NaN   NaN   NaN  41.0   NaN   NaN  ...
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...
195.0      NaN   NaN   NaN   NaN   NaN   NaN  31.0  55.0   NaN   NaN  ...
196.0      NaN  29.0   NaN   NaN   NaN   NaN   NaN  41.0  57.0   NaN  ...
197.0      NaN   NaN  57.5   NaN  31.0   NaN   NaN   NaN  39.0   NaN  ...
198.0     28.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
199.0      NaN  22.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...

         Skin_Fold
Pregnant        7     8     9   10  11  12  13  14  15  17
Glucose
44.0           NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
56.0           NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
57.0           NaN   NaN  37.0 NaN NaN NaN NaN NaN NaN NaN
61.0           NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
62.0           NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
...            ...   ...   ...  ..  ..  ..  ..  ..  ..  ..
195.0         33.0   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
196.0          NaN  29.0   NaN NaN NaN NaN NaN NaN NaN NaN
197.0          NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
198.0          NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN
199.0          NaN   NaN   NaN NaN NaN NaN NaN NaN NaN NaN

[135 rows x 119 columns]